### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by marcomartinscastanho** [auth0/password-sheriff#26]
### Describe the problem you'd like to have solved
Currently, it doesn't support TypeScript

### Describe the ideal solution
Provide support for TypeScript

**Comment by evansims** [comment]
Hi, @marcomartinscastanho 👋 Thanks for your suggestion. We don't currently have any plans on introducing TypeScript support to this library; however, PRs are welcome if anyone wants to take it upon themselves.
